language: cpp

env:
    - DEBUG=0
    - DEBUG=1

install:
    - wget http://downloads.arduino.cc/arduino-1.6.1-linux64.tar.xz
    - tar -xf arduino-1.6.1-linux64.tar.xz
    - sudo mv arduino-1.6.1/ /opt/Arduino

script: make debug=$DEBUG
