language: cpp

install:
    - wget http://arduino.cc/download_handler.php?f=/arduino-1.6.1-linux64.tar.xz
    - tar -xvf arduino-1.6.1-linux64.tar.xz
    - sudo mv arduino-1.6.1/ /opt/Arduino/arduino

script: make
