language: cpp

install:
    - wget http://downloads.arduino.cc/arduino-1.6.1-linux64.tar.xz
    - tar -xf arduino-1.6.1-linux64.tar.xz
    - sudo mv arduino-1.6.1/ /opt/Arduino

script:
    - make debug=1
    - cd test/ ; make && make test
